name: Fake Release

on:
  workflow_dispatch:
#  push:
#    tags:
#    - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: CI
      run: |
        echo ci mwahahah
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    needs: [ci]
    steps:
    - name: Compile
      run: |
        mkdir dist
        touch dist/${{ matrix.os }}.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        retention-days: 1
        path: dist/

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: [build]
    steps:
    - name: Setup artifact uploads
      run: |
        mkdir art/
  
    - name: Download artifacts
      uses: actions/download-artifact@v4.1.9
      with:
        path: art/
  
    - name: Release
      uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
      with:
        tag: ${{ github.ref_name }}
        name: Test ${{ github.ref_name }}
        body: Test ${{ github.ref_name }}"
        draft: false
        prerelease: true
        artifacts: art/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
