name: Fake Release

on:
  workflow_dispatch:
#  push:
#    tags:
#    - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: CI
      run: |
        echo ci mwahahah
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    needs: [ci]
    steps:
    - name: Compile
      run: |
        mkdir dist
        touch dist/${{ matrix.os }}.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        retention-days: 1
        path: dist/

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: [build]
    steps:
    - name: Setup artifact uploads
      run: |
        mkdir art/
  
    - name: Download artifacts
      uses: actions/download-artifact@v4.1.9
      with:
        path: art/

    - name: List artifacts (debug)
      run: |
        ls art/ -f
  
    - name: Upload release (ubuntu-latest)
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: art/ubuntu-latest.zip
        asset_name: debian.zip
        tag: latest
        overwrite: true
        prerelease: true
        body: "Test Build"

    - name: Upload release (windows-latest)
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: art/windows-latest.zip
        asset_name: windows.zip
        tag: latest
        overwrite: true
        prerelease: true
        body: "Test Build"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
